colorlist1 = set(["White", "Black", "Red"])
colorlist2 = set(["Red", "Green"])
print("Original set elements:")
print(colorlist1)
print(colorlist2)
print("\ncolors from colorlist1 not contained in colorlist2:")
print(colorlist1.difference(colorlist2))
print("\nDifferenct of color_list_2 and colorlist1:")
print(colorlist2.difference(colorlist1))
